version: '3.1'


services:
    db:
        build: .

        container_name: api-db
        restart: always

        tty: true

        ports:
            - "5433:5432"

        volumes:
            - .docker/db/data:/var/lib/postgresql/data

        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=projectdb
